version: '3'

services:
  elastichsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elastichsearch
    ports: 
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - 5601:5601
    links:
      - elastichsearch:elasticsearch
    depends_on:
      - 'elastichsearch'  

volumes: 
  data01:
    driver: local
